name: main

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml
    permissions:
      checks: write
      contents: write
